import { Evaluation, Message, UserModule } from '../types';

export const evaluations: Evaluation[] = [
  {
    id: '1',
    disciplina_nome: 'Cuidados Elementares em Saude e Doencas Prevalentes',
    modulo_nome: 'Modulo 6',
    modulo_id: '6',
    professor_nome: 'Cristiane Cunha',
    data: '2025-02-24',
    horario_ini: '08:30',
    horario_fim: '10:30',
    laboratorios: [
      { id: 16, nome: 'Lab 16' },
      { id: 17, nome: 'Lab 17' },
      { id: 18, nome: 'Lab 18' },
      { id: 19, nome: 'Lab 19' },
      { id: 14, nome: 'Lab 14 (CAIP)' },
    ],
    observacoes: 'Avaliacao pratica com estacoes rotativas. Trazer jaleco e equipamentos de protecao individual.',
    isFavorite: true,
  },
  {
    id: '2',
    disciplina_nome: 'Sistema Endocrino',
    modulo_nome: '3o Periodo',
    modulo_id: '3',
    professor_nome: 'Tassio Huguenin',
    data: '2025-03-09',
    horario_ini: '10:00',
    horario_fim: '12:00',
    laboratorios: [
      { id: 8, nome: 'Lab 8' },
      { id: 9, nome: 'Lab 9' },
    ],
    observacoes: 'Avaliacao teorica sobre o sistema endocrino.',
    isFavorite: true,
  },
  {
    id: '3',
    disciplina_nome: 'Doencas Cronicas',
    modulo_nome: 'Modulo 8',
    modulo_id: '8',
    professor_nome: 'Jose Roberto Barroso',
    data: '2025-03-11',
    horario_ini: '07:30',
    horario_fim: '09:30',
    laboratorios: [
      { id: 14, nome: 'Lab 14' },
      { id: 15, nome: 'Lab 15' },
    ],
    observacoes: 'Avaliacao sobre manejo de doencas cronicas.',
    isFavorite: false,
  },
  {
    id: '4',
    disciplina_nome: 'Internato I - Saude do Adulto e do Idoso',
    modulo_nome: 'Internato',
    modulo_id: 'int1',
    professor_nome: 'Luciana Oliveira',
    data: '2025-03-11',
    horario_ini: '13:00',
    horario_fim: '15:00',
    laboratorios: [
      { id: 'hu', nome: 'Hospital Universitario' },
    ],
    observacoes: 'Atividade pratica com pacientes.',
    isFavorite: true,
  },
  {
    id: '5',
    disciplina_nome: 'Internato III - Saude da Mulher',
    modulo_nome: 'Internato',
    modulo_id: 'int3',
    professor_nome: 'Mariana Figueiredo',
    data: '2025-03-18',
    horario_ini: '08:00',
    horario_fim: '10:00',
    laboratorios: [
      { id: 'gineco', nome: 'Ambulatorio de Ginecologia' },
    ],
    observacoes: 'Atendimento ambulatorial supervisionado.',
    isFavorite: false,
  },
];

export const messages: Message[] = [
  {
    id: '1',
    title: 'Avaliacao reagendada',
    body: 'Sistema Endocrino foi movida de 09/03 para 12/03/2025 as 10h.',
    time: 'Hoje, 14:22',
    isRead: false,
    type: 'warning',
  },
  {
    id: '2',
    title: 'Nova avaliacao cadastrada',
    body: 'Internato IV - Saude Mental adicionada ao Modulo 10.',
    time: 'Hoje, 11:05',
    isRead: false,
    type: 'success',
  },
  {
    id: '3',
    title: 'Lembrete de avaliacao',
    body: 'Doencas Cronicas ocorre amanha as 07:30 no Lab 14.',
    time: 'Ontem, 19:00',
    isRead: false,
    type: 'info',
  },
  {
    id: '4',
    title: 'Laboratorio alterado',
    body: 'Cuidados Elementares: lab 14 substituido pelo lab 18.',
    time: '20/02/2025',
    isRead: true,
    type: 'normal',
  },
  {
    id: '5',
    title: 'Bem-vindo ao GERAVA',
    body: 'O app de consulta de avaliacoes esta disponivel para uso.',
    time: '01/02/2025',
    isRead: true,
    type: 'normal',
  },
];

export const modules: UserModule[] = [
  { id: 1, nome: 'Modulo 1', periodo: '1o Semestre - Ciclo Basico' },
  { id: 2, nome: 'Modulo 2', periodo: '2o Semestre - Ciclo Basico' },
  { id: 3, nome: '3o Periodo', periodo: 'Sistema Endocrino e afins' },
  { id: 4, nome: 'Modulo 4', periodo: '4o Semestre' },
  { id: 5, nome: 'Modulo 5', periodo: '5o Semestre' },
  { id: 6, nome: 'Modulo 6 (7147)', periodo: 'Cuidados Elementares' },
  { id: 7, nome: 'Modulo 7', periodo: '7o Semestre' },
  { id: 8, nome: 'Modulo 8 (7149)', periodo: 'Doencas Cronicas' },
  { id: 9, nome: 'Internato', periodo: 'Ciclo Clinico Final' },
];
