// src/constants/data.ts
import { Evaluation, Message, UserModule } from '../types';

export const evaluations: Evaluation[] = [
  {
    id: '1',
    title: 'Cuidados Elementares em Saúde e Doenças Prevalentes',
    module: 'Módulo 6',
    moduleId: '6',
    professor: 'Cristiane Cunha',
    date: '2025-02-24',
    time: '08:30',
    duration: '2h',
    labs: ['Lab 16', 'Lab 17', 'Lab 18', 'Lab 19', 'Lab 14 (CAIP)'],
    observations: 'Avaliação prática com estações rotativas. Trazer jaleco e equipamentos de proteção individual.',
    isFavorite: true,
    moduleType: 'module',
  },
  {
    id: '2',
    title: 'Sistema Endócrino',
    module: '3º Período',
    moduleId: '3',
    professor: 'Tássio Huguenin',
    date: '2025-03-09',
    time: '10:00',
    duration: '2h',
    labs: ['Lab 8', 'Lab 9'],
    observations: 'Avaliação teórica sobre o sistema endócrino.',
    isFavorite: true,
    moduleType: 'period',
  },
  {
    id: '3',
    title: 'Doenças Crônicas',
    module: 'Módulo 8',
    moduleId: '8',
    professor: 'José Roberto Barroso',
    date: '2025-03-11',
    time: '07:30',
    duration: '2h',
    labs: ['Lab 14', 'Lab 15'],
    observations: 'Avaliação sobre manejo de doenças crônicas.',
    isFavorite: false,
    moduleType: 'module',
  },
  {
    id: '4',
    title: 'Internato I – Saúde do Adulto e do Idoso',
    module: 'Internato',
    moduleId: 'int1',
    professor: 'Luciana Oliveira',
    date: '2025-03-11',
    time: '13:00',
    duration: '2h',
    labs: ['Hospital Universitário'],
    observations: 'Atividade prática com pacientes.',
    isFavorite: true,
    moduleType: 'internship',
  },
  {
    id: '5',
    title: 'Internato III – Saúde da Mulher',
    module: 'Internato',
    moduleId: 'int3',
    professor: 'Mariana Figueiredo',
    date: '2025-03-18',
    time: '08:00',
    duration: '2h',
    labs: ['Ambulatório de Ginecologia'],
    observations: 'Atendimento ambulatorial supervisionado.',
    isFavorite: false,
    moduleType: 'internship',
  },
];

export const messages: Message[] = [
  {
    id: '1',
    title: 'Avaliação reagendada',
    body: 'Sistema Endócrino foi movida de 09/03 para 12/03/2025 às 10h.',
    time: 'Hoje, 14:22',
    isRead: false,
    type: 'warning',
  },
  {
    id: '2',
    title: 'Nova avaliação cadastrada',
    body: 'Internato IV – Saúde Mental adicionada ao Módulo 10.',
    time: 'Hoje, 11:05',
    isRead: false,
    type: 'success',
  },
  {
    id: '3',
    title: 'Lembrete de avaliação',
    body: 'Doenças Crônicas ocorre amanhã às 07:30 no Lab 14.',
    time: 'Ontem, 19:00',
    isRead: false,
    type: 'info',
  },
  {
    id: '4',
    title: 'Laboratório alterado',
    body: 'Cuidados Elementares: lab 14 substituído pelo lab 18.',
    time: '20/02/2025',
    isRead: true,
    type: 'normal',
  },
  {
    id: '5',
    title: 'Bem-vindo ao GERAVA',
    body: 'O app de consulta de avaliações está disponível para uso.',
    time: '01/02/2025',
    isRead: true,
    type: 'normal',
  },
];

export const modules: UserModule[] = [
  { id: 1, name: 'Módulo 1', period: '1º Semestre · Ciclo Básico', isSelected: false },
  { id: 2, name: 'Módulo 2', period: '2º Semestre · Ciclo Básico', isSelected: false },
  { id: 3, name: '3º Período', period: 'Sistema Endócrino e afins', isSelected: false },
  { id: 4, name: 'Módulo 4', period: '4º Semestre', isSelected: false },
  { id: 5, name: 'Módulo 5', period: '5º Semestre', isSelected: false },
  { id: 6, name: 'Módulo 6 (7147)', period: 'Cuidados Elementares', isSelected: true },
  { id: 7, name: 'Módulo 7', period: '7º Semestre', isSelected: false },
  { id: 8, name: 'Módulo 8 (7149)', period: 'Doenças Crônicas', isSelected: false },
  { id: 9, name: 'Internato', period: 'Ciclo Clínico Final', isSelected: false },
];